#############################################################################
# Makefile for building: E-Gold-qt
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  egd-qt.pro
# Template: app
# Command: e:/deps/5.2.1/bin/qmake.exe RELEASE=1 USE_UPNP=1 USE_QRCODE=1 -o Makefile egd-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = e:/deps/5.2.1/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: egd-qt.pro ../5.2.1/mkspecs/win32-g++/qmake.conf ../5.2.1/mkspecs/features/spec_pre.prf \
		../5.2.1/mkspecs/qdevice.pri \
		../5.2.1/mkspecs/features/device_config.prf \
		../5.2.1/mkspecs/common/shell-unix.conf \
		../5.2.1/mkspecs/qconfig.pri \
		../5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../5.2.1/mkspecs/modules-inst/qt_lib_clucene_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_clucene_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_concurrent.pri \
		../5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_core.pri \
		../5.2.1/mkspecs/modules/qt_lib_core_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_gui.pri \
		../5.2.1/mkspecs/modules/qt_lib_gui_private.pri \
		../5.2.1/mkspecs/modules-inst/qt_lib_help.pri \
		../5.2.1/mkspecs/modules-inst/qt_lib_help_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_help.pri \
		../5.2.1/mkspecs/modules/qt_lib_network.pri \
		../5.2.1/mkspecs/modules/qt_lib_network_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_printsupport.pri \
		../5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_sql.pri \
		../5.2.1/mkspecs/modules/qt_lib_sql_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_testlib.pri \
		../5.2.1/mkspecs/modules/qt_lib_testlib_private.pri \
		../5.2.1/mkspecs/modules-inst/qt_lib_uitools.pri \
		../5.2.1/mkspecs/modules-inst/qt_lib_uitools_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_uitools.pri \
		../5.2.1/mkspecs/modules/qt_lib_widgets.pri \
		../5.2.1/mkspecs/modules/qt_lib_widgets_private.pri \
		../5.2.1/mkspecs/modules/qt_lib_xml.pri \
		../5.2.1/mkspecs/modules/qt_lib_xml_private.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qico.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qminimal.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../5.2.1/mkspecs/modules/qt_plugin_qwindows.pri \
		../5.2.1/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../5.2.1/mkspecs/modules/qt_tool_lconvert.pri \
		../5.2.1/mkspecs/modules/qt_tool_lrelease.pri \
		../5.2.1/mkspecs/modules/qt_tool_lupdate.pri \
		../5.2.1/mkspecs/modules/qt_tool_qdoc.pri \
		../5.2.1/mkspecs/modules/qt_tool_syncqt.pri \
		../5.2.1/mkspecs/modules/qt_tool_uic.pri \
		../5.2.1/mkspecs/features/qt_functions.prf \
		../5.2.1/mkspecs/features/qt_config.prf \
		../5.2.1/mkspecs/win32-g++/qmake.conf \
		../5.2.1/mkspecs/features/spec_post.prf \
		../5.2.1/mkspecs/features/exclusive_builds.prf \
		../5.2.1/mkspecs/features/default_pre.prf \
		../5.2.1/mkspecs/features/win32/default_pre.prf \
		../5.2.1/mkspecs/features/resolve_config.prf \
		../5.2.1/mkspecs/features/exclusive_builds_post.prf \
		../5.2.1/mkspecs/features/default_post.prf \
		../5.2.1/mkspecs/features/qt.prf \
		../5.2.1/mkspecs/features/resources.prf \
		../5.2.1/mkspecs/features/moc.prf \
		../5.2.1/mkspecs/features/uic.prf \
		../5.2.1/mkspecs/features/win32/rtti.prf \
		../5.2.1/mkspecs/features/warn_on.prf \
		../5.2.1/mkspecs/features/win32/windows.prf \
		../5.2.1/mkspecs/features/testcase_targets.prf \
		../5.2.1/mkspecs/features/exceptions.prf \
		../5.2.1/mkspecs/features/yacc.prf \
		../5.2.1/mkspecs/features/lex.prf \
		egd-qt.pro \
		E:/deps/5.2.1/lib/Qt5Widgets.prl \
		E:/deps/5.2.1/lib/Qt5Gui.prl \
		E:/deps/5.2.1/lib/Qt5Core.prl \
		E:/deps/5.2.1/lib/Qt5Network.prl \
		E:/deps/5.2.1/plugins/platforms/qwindows.prl \
		E:/deps/5.2.1/lib/Qt5PlatformSupport.prl
	$(QMAKE) RELEASE=1 USE_UPNP=1 USE_QRCODE=1 -o Makefile egd-qt.pro
../5.2.1/mkspecs/features/spec_pre.prf:
../5.2.1/mkspecs/qdevice.pri:
../5.2.1/mkspecs/features/device_config.prf:
../5.2.1/mkspecs/common/shell-unix.conf:
../5.2.1/mkspecs/qconfig.pri:
../5.2.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
../5.2.1/mkspecs/modules-inst/qt_lib_clucene_private.pri:
../5.2.1/mkspecs/modules/qt_lib_clucene_private.pri:
../5.2.1/mkspecs/modules/qt_lib_concurrent.pri:
../5.2.1/mkspecs/modules/qt_lib_concurrent_private.pri:
../5.2.1/mkspecs/modules/qt_lib_core.pri:
../5.2.1/mkspecs/modules/qt_lib_core_private.pri:
../5.2.1/mkspecs/modules/qt_lib_gui.pri:
../5.2.1/mkspecs/modules/qt_lib_gui_private.pri:
../5.2.1/mkspecs/modules-inst/qt_lib_help.pri:
../5.2.1/mkspecs/modules-inst/qt_lib_help_private.pri:
../5.2.1/mkspecs/modules/qt_lib_help.pri:
../5.2.1/mkspecs/modules/qt_lib_network.pri:
../5.2.1/mkspecs/modules/qt_lib_network_private.pri:
../5.2.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
../5.2.1/mkspecs/modules/qt_lib_printsupport.pri:
../5.2.1/mkspecs/modules/qt_lib_printsupport_private.pri:
../5.2.1/mkspecs/modules/qt_lib_sql.pri:
../5.2.1/mkspecs/modules/qt_lib_sql_private.pri:
../5.2.1/mkspecs/modules/qt_lib_testlib.pri:
../5.2.1/mkspecs/modules/qt_lib_testlib_private.pri:
../5.2.1/mkspecs/modules-inst/qt_lib_uitools.pri:
../5.2.1/mkspecs/modules-inst/qt_lib_uitools_private.pri:
../5.2.1/mkspecs/modules/qt_lib_uitools.pri:
../5.2.1/mkspecs/modules/qt_lib_widgets.pri:
../5.2.1/mkspecs/modules/qt_lib_widgets_private.pri:
../5.2.1/mkspecs/modules/qt_lib_xml.pri:
../5.2.1/mkspecs/modules/qt_lib_xml_private.pri:
../5.2.1/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../5.2.1/mkspecs/modules/qt_plugin_qico.pri:
../5.2.1/mkspecs/modules/qt_plugin_qminimal.pri:
../5.2.1/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../5.2.1/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../5.2.1/mkspecs/modules/qt_plugin_qwindows.pri:
../5.2.1/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../5.2.1/mkspecs/modules/qt_tool_lconvert.pri:
../5.2.1/mkspecs/modules/qt_tool_lrelease.pri:
../5.2.1/mkspecs/modules/qt_tool_lupdate.pri:
../5.2.1/mkspecs/modules/qt_tool_qdoc.pri:
../5.2.1/mkspecs/modules/qt_tool_syncqt.pri:
../5.2.1/mkspecs/modules/qt_tool_uic.pri:
../5.2.1/mkspecs/features/qt_functions.prf:
../5.2.1/mkspecs/features/qt_config.prf:
../5.2.1/mkspecs/win32-g++/qmake.conf:
../5.2.1/mkspecs/features/spec_post.prf:
../5.2.1/mkspecs/features/exclusive_builds.prf:
../5.2.1/mkspecs/features/default_pre.prf:
../5.2.1/mkspecs/features/win32/default_pre.prf:
../5.2.1/mkspecs/features/resolve_config.prf:
../5.2.1/mkspecs/features/exclusive_builds_post.prf:
../5.2.1/mkspecs/features/default_post.prf:
../5.2.1/mkspecs/features/qt.prf:
../5.2.1/mkspecs/features/resources.prf:
../5.2.1/mkspecs/features/moc.prf:
../5.2.1/mkspecs/features/uic.prf:
../5.2.1/mkspecs/features/win32/rtti.prf:
../5.2.1/mkspecs/features/warn_on.prf:
../5.2.1/mkspecs/features/win32/windows.prf:
../5.2.1/mkspecs/features/testcase_targets.prf:
../5.2.1/mkspecs/features/exceptions.prf:
../5.2.1/mkspecs/features/yacc.prf:
../5.2.1/mkspecs/features/lex.prf:
egd-qt.pro:
E:/deps/5.2.1/lib/Qt5Widgets.prl:
E:/deps/5.2.1/lib/Qt5Gui.prl:
E:/deps/5.2.1/lib/Qt5Core.prl:
E:/deps/5.2.1/lib/Qt5Network.prl:
E:/deps/5.2.1/plugins/platforms/qwindows.prl:
E:/deps/5.2.1/lib/Qt5PlatformSupport.prl:
qmake: FORCE
	@$(QMAKE) RELEASE=1 USE_UPNP=1 USE_QRCODE=1 -o Makefile egd-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) E:/deps/egd/e-gold-qt_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
